### ISSUE TITLE
sorting packages by version should not use the pretty version for version_compare

### ISSUE THREAD

**Issue by stof** [thecodingmachine/packanalyst#10]
https://github.com/thecodingmachine/packanalyst/blob/8cc087a6cf4b21eb726ee1c19e27629f4093d39a/src/Mouf/Packanalyst/Services/FetchDataService.php#L264-L275 is sorting versions with ``version_compare`` based on their pretty version. But this is wrong. Pretty versions may have a different number of parts in their version (it could be ``v2.0`` for the 2.0.0 release) or other chars (``2.x-dev`` for a dev branch) which are not handled properly by ``version_compare``.
To sort packages, you should rely on the normalized package version (the normalization is precisely applied to make sure ``version_compare`` will sort versions properly)

**Comment by moufmouf** [comment]
I'm not aware of a case where this was triggering a bug but I'll grant you it is way cleaner to use the normalized version.
Fixed.
