### ISSUE TITLE
[Suggestion] Use PSR-2 coding standards

### ISSUE THREAD

**Issue by stof** [thecodingmachine/packanalyst#19]
Currently, the coding standards used in the project are not matching PSR-2. What do you think about using PSR-2 instead ?

**Comment by stof** [comment]
Note that https://github.com/FriendsOfPHP/PHP-CS-Fixer can help switching to PSR-2, as it can apply many of the PSR-2 rules by itself (be careful that the default config in the 1.x versions is to apply the Symfony coding standards though, which include much more rules than PSR-2)

**Comment by moufmouf** [comment]
Completely agree. I'm following PSR-2 on all my recent projects. Packanalyst was just written before I took this habit. Will fix.
