### ISSUE TITLE
Accessing the mouf admin interface complains about resources/messages.php

### ISSUE THREAD

**Issue by stof** [thecodingmachine/packanalyst#22]
It says that this file does not exist and asks to create it. But then, this file is not ignored in the project. Should it be added in .gitignore, be created and committed, or is the Mouf admin interface showoing a red flag about something unnecessary for the project ?

**Comment by moufmouf** [comment]
Fine is the translation service coming with Mouf. It is loaded as a dependency of the MVC framework (something that will be fixed in the future version). Since I'm not using translation in Packanalyst, the message is not needed.

I'll create the empty file to remove the warning anyway.
