### ISSUE TITLE
What state is API in?

### ISSUE THREAD

**Issue by TomasVotruba** [thecodingmachine/packanalyst#36]
I've noticed API note on the web: http://packanalyst.com/#api

And I'm very curious :) 

I'd love to use it to get most active dependencies of specific package, e.g. `phpunit/phpunit`
to get entry packages to [Rector](https://github.com/rectorphp/rector)

**Comment by TomasVotruba** [comment]
Outdated

**Comment by Wulfheart** [comment]
Well. Not outdated. I’m also curious.
