### ISSUE TITLE
Show which packages use the current package

### ISSUE THREAD

**Issue by colinodell** [thecodingmachine/packanalyst#4]
Here's the package listing for a library I maintain:  http://packanalyst.com/package?name=league%2Fcommonmark

It would be cool to see which packages use mine.  Right now I'd have to click into different classes to see this information, which is tedious.  Why not provide a list somewhere of all the packages which require mine?

**Comment by colinodell** [comment]
It looks like versioneye.com does something similar: https://www.versioneye.com/php/league:commonmark/references

**Comment by stof** [comment]
This is now provided on Packagist itself.

**Comment by colinodell** [comment]
Oh awesome!  I'll go ahead and close this then, since Packagist provides exactly what I'm looking for.  Thanks!

**Comment by stof** [comment]
for reference for people reading this issue later, this is provided on https://packagist.org/packages/league/commonmark/dependents (accessible through the ``Dependents`` link in the right column of the package page)
