### ISSUE TITLE
http://packanalyst.com is down

### ISSUE THREAD

**Issue by rodion-k** [thecodingmachine/packanalyst#40]
503 Service Temporarily Unavailable

**Comment by moufmouf** [comment]
Indeed!

The service is back up, following a service migration, but all data was lost and we are currently re-indexing all PHP packages.... which takes a loooooooooong time (it has already been running for several weeks). So Packanalyst is up but results are probably partial right now.

**Comment by rodion-k** [comment]
Thanks! The project is awesome!
